//-----------------------------------------------------------------------
// <copyright file="MQiushibaike.cs" company="517 Enterprises">
//      Copyright (c) 517 Enterprises. All rights reserved.
// </copyright>
// <date>2016/1/13 10:12:23</date>
// <Author>auto generated by .xla</Author>
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace Tzq.WeChatService.Model
{
    /// <summary>
    /// 糗事百科
    /// </summary>
    [DataContract]
    public class MQiushibaike
    {
        #region private members

        /// <summary>
        ///  主键
        /// </summary>
        private string keyID = string.Empty;

        /// <summary>
        ///  糗友ID
        /// </summary>
        private string jokerName = string.Empty;

        /// <summary>
        ///  笑话内容
        /// </summary>
        private string jokeContent = string.Empty;

        /// <summary>
        ///  获得赞的个数
        /// </summary>
        private int lauds;

        /// <summary>
        ///  是否删除
        /// </summary>
        private int isDelete;

        #endregion

        #region construction

        /// <summary>
        /// 构造函数
        /// </summary>
        public MQiushibaike()
        {
        }

        #endregion

        #region public members

        /// <summary>
        /// 主键
        /// </summary>
        [DataMember]
        public string KeyID
        {
            get { return this.keyID; }
            set { this.keyID = value; }
        }

        /// <summary>
        /// 糗友ID
        /// </summary>
        [DataMember]
        public string JokerName
        {
            get { return this.jokerName; }
            set { this.jokerName = value; }
        }

        /// <summary>
        /// 笑话内容
        /// </summary>
        [DataMember]
        public string JokeContent
        {
            get { return this.jokeContent; }
            set { this.jokeContent = value; }
        }

        /// <summary>
        /// 获得赞的个数
        /// </summary>
        [DataMember]
        public int Lauds
        {
            get { return this.lauds; }
            set { this.lauds = value; }
        }

        /// <summary>
        /// 是否删除
        /// </summary>
        [DataMember]
        public int IsDelete
        {
            get { return this.isDelete; }
            set { this.isDelete = value; }
        }

        #endregion

    }
}